services:
  postgres-catalogo:
    image: postgres:16-alpine
    container_name: postgres-catalogo
    environment:
      POSTGRES_DB: db_catalogo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata-catalogo:/var/lib/postgresql/data

  floci:
    image: floci/floci:latest
    container_name: floci
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    environment:
      FLOCI_SERVICES_EKS_DOCKER_NETWORK: vehicle-catalog-service_default

networks:
  default:
    name: vehicle-catalog-service_default

volumes:
  pgdata-catalogo:
