apiVersion: v1
kind: Secret
metadata:
  name: vehicle-catalog-secrets
type: Opaque
data:
  spring-datasource-password: YWRtaW4xMjM=
  jwt-secret: OWE3MjYyMTc0YzEwNjQzN2EzNDZmOTA2YjNhMGU2N2UzZGZkMzY0ODBiMjcxM2UzM2U5ZDgwZDJjZjM0ZDU4OA==
