apiVersion: v1
kind: Secret
metadata:
  name: vehicle-sales-secrets
type: Opaque
data:
  spring-datasource-password: cG9zdGdyZXM=
  jwt-secret: OWE3MjYyMTc0YzEwNjQzN2EzNDZmOTA2YjNhMGU2N2UzZGZkMzY0ODBiMjcxM2UzM2U5ZDgwZDJjZjM0ZDU4OA==
  hmac-secret: c3VwZXItc2VjcmV0LWhtYWMtc2lnbmF0dXJlLWtleS1mb3Itd2ViaG9vay12YWxpZGF0aW9uLTIwMjY=
