apiVersion: v1
kind: Service
metadata:
  name: vehicle-sales-service
  labels:
    app: vehicle-sales-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: vehicle-sales-service
  type: ClusterIP
